version: '3.5'
services:
  database:
    build:
      context: .
      dockerfile: DBDockerfile
    container_name: postgresdb
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ratestask
      - POSTGRES_DB=postgres


  flask:
    build:
      context: .
      dockerfile: Dockerfile
    environment: # or use env_file as you did above
      USER: postgres
      PASS: ratestask
      HOST: database     # This is the name of the database service in this file above
      PORT: 5432
      DATABASE: postgres
    depends_on:
      - database
    command:
      - python -m unittest test.py
    restart: unless-stopped
