version: '3.5'
services:
  database:
    build:
      context: ..
      dockerfile: docker-files/DBDockerfile
    container_name: postgresdb
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ratestask
      - POSTGRES_DB=postgres


  flask:
    build:
      context: ..
      dockerfile: docker-files/Dockerfile
    environment:
      USER: postgres
      PASS: ratestask
      HOST: database
      PORT: 5432
      DATABASE: postgres
    depends_on:
      - database
    restart: unless-stopped
